//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_avis
    {
        public int id { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
        public double Note { get; set; }
        public int idFormation { get; set; }
        public System.DateTime DateAvis { get; set; }
    
        public virtual dbo_formation dbo_formation { get; set; }
    }
}
